name: Poll
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      region:
        type: choice
        options: [all, global, korea, china, taiwan]
        default: all
      full:
        type: boolean
        default: false

concurrency:
  group: write
  cancel-in-progress: false

jobs:
  poll:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        region: [global, korea, china, taiwan]
    steps:
      - uses: actions/checkout@v6
      - uses: robinraju/release-downloader@v1
        with:
          repository: WorkingRobot/ffxiv-downloader
          latest: true
          fileName: xiv-dl-linux-x64
      - run: chmod +x xiv-dl-linux-x64 && mv xiv-dl-linux-x64 xiv-dl
      - if: inputs.region == '' || inputs.region == 'all' || inputs.region == matrix.region
        run: ./xiv-dl --verbose poll -r ${{ matrix.region }} --path . ${{ inputs.full && '--full' || '' }}
      - run: rm -f xiv-dl && ./.github/push.sh "poll ${{ matrix.region }}"
        shell: bash
